CREATE TABLE IF NOT EXISTS api_hits (ts TIMESTAMP SORTKEY ENCODE delta, api VARCHAR(256) ENCODE lzo, key VARCHAR(256) DISTKEY ENCODE lzo, status VARCHAR(256) ENCODE lzo, origin VARCHAR(256) ENCODE lzo, duplicate BOOLEAN);

CREATE TABLE IF NOT EXISTS pelias_traffic_v2 (date TIMESTAMP SORTKEY ENCODE delta, api_key VARCHAR(100) DISTKEY ENCODE lzo, path VARCHAR(250) ENCODE lzo, query VARCHAR(400) ENCODE lzo, status INTEGER ENCODE lzo, http_method VARCHAR(100) ENCODE lzo, cache_hit BOOLEAN, total_ms INTEGER ENCODE lzo, first_byte_ms INTEGER ENCODE lzo);

CREATE TABLE IF NOT EXISTS vector_traffic_v2 (date TIMESTAMP SORTKEY ENCODE delta, payload_size INTEGER ENCODE lzo, source VARCHAR(100) ENCODE lzo, layer VARCHAR(100) ENCODE lzo, x INTEGER ENCODE lzo, y INTEGER ENCODE lzo, z SMALLINT ENCODE lzo, format VARCHAR(100) ENCODE lzo, api_key VARCHAR(100) DISTKEY ENCODE lzo, status SMALLINT ENCODE lzo, cache_hit BOOLEAN, total_ms INTEGER ENCODE lzo, first_byte_ms INTEGER ENCODE lzo);
